### ISSUE TITLE
SPEC fields not up to date

### ISSUE THREAD

**Issue by rinigus** [james1465/harbour-cellmate#1]
Hi!

Thank you for submitting the project to Chum OBS. Right now we cannot accept it as there are few fields which are not updated in the SPEC file:

- License in SPEC is not set
- URL points to example.com
- Chum SPEC section points to piggz screenshots

Please fix those and resubmit

**Comment by james1465** [comment]
Thanks for checking these. I've fixed the spec file over several commits

**Comment by rinigus** [comment]
Thanks!

**Comment by rinigus** [comment]
Just as a feedback:

- you don't have to have all fields set in Chum section. So, if there is no icon, its better not to have package icon defined there :)
- package is in chum:testing now and you can check whether it builds as expected and change it accordingly. You are maintainer of it in testing repo. 
- before submitting to sailfishos:chum at OBS, make sure that you set the revision in _service file.
